extern crate decoder_macro;
use super::OpcodeDecoder;
use decoder_macro::OpcodeDecoder;

use crate::sixty_five::data_types::{Byte, Word};

#[repr(u8)]
#[derive(OpcodeDecoder)]
pub enum Opcode {
    LoadAImmediate(Byte) = 0xa9,
    LoadAZeroPage(Byte) = 0xa5,
    LoadAZeroPageX(Byte) = 0xb5,
    LoadAAbsolute(Word) = 0xad,
    LoadXImmediate(Byte) = 0xa2,
    LoadYImmediate(Byte) = 0xa0,
    StoreAZeroPage(Byte) = 0x85,
    StoreAZeroPageX(Byte) = 0x95,
    StoreAAbsolute(Word) = 0x8d,
    StoreAAbsoluteX(Word) = 0x9d,
    StoreAAbsoluteY(Word) = 0x99,
    StoreAIndirectX(Byte) = 0x81,
    StoreAIndirectY(Byte) = 0x91,
    StoreXZeroPage(Byte) = 0x86,
    StoreXZeroPageY(Byte) = 0x96,
    StoreXAbsolute(Word) = 0x8e,
    StoreYZeroPage(Byte) = 0x84,
    StoreYZeroPageX(Byte) = 0x94,
    StoreYAbsolute(Word) = 0x8c,
    MoveAY = 0xa8,
    MoveAX = 0xaa,
    MoveSX = 0xba,
    MoveYA = 0x89,
    MoveXA = 0x8a,
    MoveXS = 0x9a,
    AddImmediate(Byte) = 0x69,
    AddCarryZero(Byte) = 0x65,
    AndImm(Byte) = 0x29,
    AndZero(Byte) = 0x25,
    AndZeroX(Byte) = 0x35,
    AndAbs(Word) = 0x2d,
    AndAbsX(Word) = 0x3d,
    AndAbsY(Word) = 0x39,
    AndIndX(Byte) = 0x21,
    AndIndY(Byte) = 0x31,
    JumpAbs(Word) = 0x4c,
    JumpInd(Word) = 0x6c,
    IncX = 0xe8,
    DecX = 0xca,
    IncY = 0xc8,
    DecY = 0x88,
    NoOp = 0xea,
    BranchCarryClear(Byte) = 0x90,
    BranchCarrySet(Byte) = 0xb0,
    BranchEqual(Byte) = 0xf0,
    BranchMinus(Byte) = 0x30,
    BranchNotEqual(Byte) = 0xd0,
    BranchPositive(Byte) = 0x10,
    BitTestZero(Byte) = 0x24,
    BitTestAbs(Word) = 0x2c,
    LShiftAcc = 0x0a,
    CompYImm(Byte) = 0xc0,
    InterruptDisable = 0x78,
    ClearDecimalMode = 0xd8,
    ClearCarry = 0x18,
    Break = 0x00,
}
